## Lexers make file
LEXER_OBJS = \
	lexers/LexA68k.o\
	lexers/LexAbaqus.o\
	lexers/LexAda.o\
	lexers/LexAPDL.o\
	lexers/LexAsm.o\
	lexers/LexAsn1.o\
	lexers/LexASY.o\
	lexers/LexAU3.o\
	lexers/LexAVE.o\
	lexers/LexAVS.o\
	lexers/LexBaan.o\
	lexers/LexBash.o\
	lexers/LexBasic.o\
	lexers/LexBullant.o\
	lexers/LexCaml.o\
	lexers/LexCLW.o\
	lexers/LexCmake.o\
	lexers/LexCOBOL.o\
	lexers/LexCoffeeScript.o\
	lexers/LexConf.o\
	lexers/LexCPP.o\
	lexers/LexCrontab.o\
	lexers/LexCsound.o\
	lexers/LexCSS.o\
	lexers/LexD.o\
	lexers/LexEiffel.o\
	lexers/LexErlang.o\
	lexers/LexEScript.o\
	lexers/LexFlagship.o\
	lexers/LexForth.o\
	lexers/LexFortran.o\
	lexers/LexGAP.o\
	lexers/LexGui4Cli.o\
	lexers/LexHaskell.o\
	lexers/LexHTML.o\
	lexers/LexInno.o\
	lexers/LexKix.o\
	lexers/LexLisp.o\
	lexers/LexLout.o\
	lexers/LexLua.o\
	lexers/LexMagik.o\
	lexers/LexMarkdown.o\
	lexers/LexMatlab.o\
	lexers/LexMetapost.o\
	lexers/LexMMIXAL.o\
	lexers/LexModula.o\
	lexers/LexMPT.o\
	lexers/LexMSSQL.o\
	lexers/LexMySQL.o\
	lexers/LexNimrod.o\
	lexers/LexNsis.o\
	lexers/LexOpal.o\
	lexers/LexOthers.o\
	lexers/LexPascal.o\
	lexers/LexPB.o\
	lexers/LexPerl.o\
	lexers/LexPLM.o\
	lexers/LexPOV.o\
	lexers/LexPowerPro.o\
	lexers/LexPowerShell.o\
	lexers/LexProgress.o\
	lexers/LexPS.o\
	lexers/LexPython.o\
	lexers/LexR.o\
	lexers/LexRebol.o\
	lexers/LexRuby.o\
	lexers/LexScriptol.o\
	lexers/LexSmalltalk.o\
	lexers/LexSML.o\
	lexers/LexSorcus.o\
	lexers/LexSpecman.o\
	lexers/LexSpice.o\
	lexers/LexSQL.o\
	lexers/LexTACL.o\
	lexers/LexTADS3.o\
	lexers/LexTAL.o\
	lexers/LexTCL.o\
	lexers/LexTCMD.o\
	lexers/LexTeX.o\
	lexers/LexTxt2tags.o\
	lexers/LexVB.o\
	lexers/LexVerilog.o\
	lexers/LexVHDL.o\
	lexers/LexYAML.o

LEXER_SRCS = \
	lexers/LexA68k.cxx\
	lexers/LexAbaqus.cxx\
	lexers/LexAda.cxx\
	lexers/LexAPDL.cxx\
	lexers/LexAsm.cxx\
	lexers/LexAsn1.cxx\
	lexers/LexASY.cxx\
	lexers/LexAU3.cxx\
	lexers/LexAVE.cxx\
	lexers/LexAVS.cxx\
	lexers/LexBaan.cxx\
	lexers/LexBash.cxx\
	lexers/LexBasic.cxx\
	lexers/LexBullant.cxx\
	lexers/LexCaml.cxx\
	lexers/LexCLW.cxx\
	lexers/LexCmake.cxx\
	lexers/LexCOBOL.cxx\
	lexers/LexCoffeeScript.cxx\
	lexers/LexConf.cxx\
	lexers/LexCPP.cxx\
	lexers/LexCrontab.cxx\
	lexers/LexCsound.cxx\
	lexers/LexCSS.cxx\
	lexers/LexD.cxx\
	lexers/LexEiffel.cxx\
	lexers/LexErlang.cxx\
	lexers/LexEScript.cxx\
	lexers/LexFlagship.cxx\
	lexers/LexForth.cxx\
	lexers/LexFortran.cxx\
	lexers/LexGAP.cxx\
	lexers/LexGui4Cli.cxx\
	lexers/LexHaskell.cxx\
	lexers/LexHTML.cxx\
	lexers/LexInno.cxx\
	lexers/LexKix.cxx\
	lexers/LexLisp.cxx\
	lexers/LexLout.cxx\
	lexers/LexLua.cxx\
	lexers/LexMagik.cxx\
	lexers/LexMarkdown.cxx\
	lexers/LexMatlab.cxx\
	lexers/LexMetapost.cxx\
	lexers/LexMMIXAL.cxx\
	lexers/LexModula.cxx\
	lexers/LexMPT.cxx\
	lexers/LexMSSQL.cxx\
	lexers/LexMySQL.cxx\
	lexers/LexNimrod.cxx\
	lexers/LexNsis.cxx\
	lexers/LexOpal.cxx\
	lexers/LexOthers.cxx\
	lexers/LexPascal.cxx\
	lexers/LexPB.cxx\
	lexers/LexPerl.cxx\
	lexers/LexPLM.cxx\
	lexers/LexPOV.cxx\
	lexers/LexPowerPro.cxx\
	lexers/LexPowerShell.cxx\
	lexers/LexProgress.cxx\
	lexers/LexPS.cxx\
	lexers/LexPython.cxx\
	lexers/LexR.cxx\
	lexers/LexRebol.cxx\
	lexers/LexRuby.cxx\
	lexers/LexScriptol.cxx\
	lexers/LexSmalltalk.cxx\
	lexers/LexSML.cxx\
	lexers/LexSorcus.cxx\
	lexers/LexSpecman.cxx\
	lexers/LexSpice.cxx\
	lexers/LexSQL.cxx\
	lexers/LexTACL.cxx\
	lexers/LexTADS3.cxx\
	lexers/LexTAL.cxx\
	lexers/LexTCL.cxx\
	lexers/LexTCMD.cxx\
	lexers/LexTeX.cxx\
	lexers/LexTxt2tags.cxx\
	lexers/LexVB.cxx\
	lexers/LexVerilog.cxx\
	lexers/LexVHDL.cxx\
	lexers/LexYAML.cxx
